### ISSUE TITLE
Ability to instantiate steps from template

### ISSUE THREAD

**Issue by ivangeorgiev** [vancun/nipybuilder#1]
1. List of steps is defined in the pipeline descriptor
2. Step template name is specified as 'activity'.
3. (Contract) Step template is a Process Group
4. List of variables to be set on the step Process Group could be specified (optional)
5. Variable values support Python string template, resolved against parameters
6. Properties for processors to be set could be specified (optional)
7. Property values support Python string template, resolved against parameters

**Example step definition (yaml):**
```yaml
steps:
 - name: Store
    activity: tpl_StoreAzureBlob
    variables:
      sdp_dir_root: '{dir_root}'
      sdp_blob_storage_container: '{blob_storage_container}'
    properties:
      PutAzureBlobStorage:
          storage-account-name: '{blob_storage_account}'
          storage-account-key: '{blob_storage_key}'
```
